"""Producer command definitions."""

PRODUCER_COMMANDS = (
    'install-producer-runtime',
    'update-producer-runtime',
    'publish-authority-package',
    'smoke-test',
    'authority',
    'derive-artifacts',
    'derive-design-package',
    'evaluate-derivation-readiness',
    'derive-implementation-plan',
    'materialize-component-spec',
    'implementation-plan-progress',
    'set-implementation-plan-activity-state',
    'derive-next-activity-bundle',
    'reconcile-implementation-plan-progress',
    'assemble-coder-brief',
    'author-brief-targets',
    'review-coder-brief',
    'prepare-architect-packet',
    'materialize-readiness',
    'materialize-verification-obligations',
    'load-issue-into-paa',
)
