from __future__ import annotations

from typing import Protocol

from paa_core.application.dto.queue import (
    QueueCheckRequest,
    QueueClaimActionRequest,
    QueueClaimNextRequest,
    QueueListClaimsRequest,
    QueueOperationResult,
    QueuePacketFileRequest,
    QueuePurgeRequest,
    QueueRepoRootRequest,
    QueueSendRequest,
    QueueValidateRequest,
)


class QueueAdminService(Protocol):
    def ensure_topology(self, request: QueueRepoRootRequest) -> QueueOperationResult: ...
    def state_info(self, request: QueueRepoRootRequest) -> QueueOperationResult: ...
    def check(self, request: QueueCheckRequest) -> QueueOperationResult: ...
    def purge(self, request: QueuePurgeRequest) -> QueueOperationResult: ...
    def validate(self, request: QueueValidateRequest) -> QueueOperationResult: ...
    def send(self, request: QueueSendRequest) -> QueueOperationResult: ...
    def claim_next(self, request: QueueClaimNextRequest) -> QueueOperationResult: ...
    def list_claims(self, request: QueueListClaimsRequest) -> QueueOperationResult: ...
    def ack(self, request: QueueClaimActionRequest) -> QueueOperationResult: ...
    def requeue(self, request: QueueClaimActionRequest) -> QueueOperationResult: ...
    def validate_packet(self, request: QueuePacketFileRequest) -> QueueOperationResult: ...
    def send_packet(self, request: QueuePacketFileRequest) -> QueueOperationResult: ...
