from __future__ import annotations

from typing import Protocol

from paa_core.application.dto.runtime import (
    RuntimeHostRunRequest,
    RuntimeLogsRequest,
    RuntimeOperationResult,
    RuntimeStatusRequest,
    RuntimeSupervisorRequest,
)


class RuntimeAdminService(Protocol):
    def run_supervisor(self, request: RuntimeSupervisorRequest) -> RuntimeOperationResult: ...
    def start_supervisor(self, request: RuntimeSupervisorRequest) -> RuntimeOperationResult: ...
    def stop_supervisor(self, request: RuntimeStatusRequest) -> RuntimeOperationResult: ...
    def supervisor_status(self, request: RuntimeStatusRequest) -> RuntimeOperationResult: ...
    def supervisor_logs(self, request: RuntimeLogsRequest) -> str: ...
    def restart_supervisor(self, request: RuntimeSupervisorRequest) -> RuntimeOperationResult: ...
    def run_techlead_host(self, request: RuntimeHostRunRequest) -> RuntimeOperationResult: ...
    def run_dev_host(self, request: RuntimeHostRunRequest) -> RuntimeOperationResult: ...
    def run_qa_host(self, request: RuntimeHostRunRequest) -> RuntimeOperationResult: ...
