"""Consumer command definitions."""

CONSUMER_COMMANDS = (
    'install-consumer-runtime',
    'update-consumer-runtime',
    'install-authority-package',
    'smoke-test',
    'queue-state-info',
    'queue-ensure-topology',
    'queue-check',
    'queue-validate',
    'queue-send',
    'techlead-validate-packet',
    'techlead-send-packet',
    'queue-claim-next',
    'queue-list-claims',
    'queue-ack',
    'queue-requeue',
    'techlead-status',
    'techlead-emit-next-assignment',
    'techlead-lineage',
    'techlead-prepare-role-branch',
    'techlead-prepare-role-worktree',
    'techlead-handoff-to-role-worktree',
    'techlead-inspect-role-worktree',
    'techlead-role-entry',
    'techlead-role-result-assist',
    'techlead-emit-decision',
    'validate-runtime',
)
