from __future__ import annotations

import argparse

from paa_core.producer.authority_acceptance import (
    cmd_advance_after_merge,
    cmd_record_acceptance,
    cmd_record_decision,
)
from paa_core.producer.authority_issues import cmd_create_issue, cmd_sync_issue
from paa_core.producer.authority_packet_results import (
    cmd_materialize_delivery_review_packet,
    cmd_materialize_qa_verification_packet,
    cmd_materialize_slice_result_packet,
    cmd_materialize_worker_result_packet,
)
from paa_core.producer.authority_packets import (
    cmd_materialize_architect_packet,
    cmd_materialize_coder_brief,
)
from paa_core.producer.authority_queries import (
    cmd_authoring_check,
    cmd_current,
    cmd_materialize_next,
    cmd_materialize_task,
    cmd_next,
    cmd_summary,
    cmd_task,
    cmd_verify_issue,
)
from paa_core.producer.authority_support import (
    PAA_PROJECT_SLUG,
    TEAM_WORKER_CLI_CHOICES,
    TEAM_WORKER_DECISION_CHOICES,
)
from paa_core.producer.authority_techlead_packets import (
    cmd_materialize_techlead_assignment_packet,
    cmd_materialize_techlead_decision_packet,
)


def build_authority_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description='Fractal Core project authority helper',
        allow_abbrev=False,
    )
    sub = parser.add_subparsers(dest='command')

    p = sub.add_parser('summary')
    p.add_argument('--manifest')
    p.set_defaults(func=cmd_summary)

    p = sub.add_parser('current')
    p.add_argument('--manifest')
    p.set_defaults(func=cmd_current)

    p = sub.add_parser('task')
    p.add_argument('--manifest')
    p.add_argument('--issue-number', type=int)
    p.add_argument('--task-id')
    p.set_defaults(func=cmd_task)

    p = sub.add_parser('next')
    p.add_argument('--manifest')
    p.add_argument('--issue-number', type=int)
    p.add_argument('--task-id')
    p.set_defaults(func=cmd_next)

    p = sub.add_parser('verify-issue')
    p.add_argument('--manifest')
    p.add_argument('--issue-number', type=int, required=True)
    p.set_defaults(func=cmd_verify_issue)

    p = sub.add_parser('authoring-check')
    p.add_argument('--manifest')
    p.add_argument('--issue-number', type=int)
    p.add_argument('--task-id')
    p.set_defaults(func=cmd_authoring_check)

    p = sub.add_parser('materialize-task')
    p.add_argument('--manifest')
    p.add_argument('--issue-number', type=int)
    p.add_argument('--task-id')
    p.add_argument('--format', choices=['json', 'markdown'], default='json')
    p.set_defaults(func=cmd_materialize_task)

    p = sub.add_parser('materialize-next')
    p.add_argument('--manifest')
    p.add_argument('--issue-number', type=int)
    p.add_argument('--task-id')
    p.add_argument('--format', choices=['json', 'markdown'], default='json')
    p.set_defaults(func=cmd_materialize_next)

    p = sub.add_parser('sync-issue')
    p.add_argument('--manifest')
    p.add_argument('--issue-number', type=int)
    p.add_argument('--task-id')
    p.set_defaults(func=cmd_sync_issue)

    p = sub.add_parser('create-issue')
    p.add_argument('--manifest')
    p.add_argument('--issue-number', type=int)
    p.add_argument('--task-id')
    p.add_argument('--force', action='store_true')
    p.set_defaults(func=cmd_create_issue)

    p = sub.add_parser('advance-after-merge')
    p.add_argument('--manifest')
    p.add_argument('--issue-number', type=int)
    p.add_argument('--task-id')
    p.add_argument('--publish', action='store_true')
    p.add_argument('--persist-db', action='store_true')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--merge-commit-sha')
    p.add_argument('--pr-number', type=int)
    p.set_defaults(func=cmd_advance_after_merge)

    p = sub.add_parser('record-acceptance')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--completed-issue-number', type=int, required=True)
    p.add_argument('--completed-task-id', required=True)
    p.add_argument('--next-issue-number', type=int)
    p.add_argument('--next-task-id')
    p.add_argument('--authority-version', required=True)
    p.add_argument('--published-at', required=True)
    p.add_argument('--merge-commit-sha')
    p.add_argument('--pr-number', type=int)
    p.set_defaults(func=cmd_record_acceptance)

    p = sub.add_parser('record-decision')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--issue-number', type=int, required=True)
    p.add_argument('--task-id', required=True)
    p.add_argument('--decision', choices=['accepted', 'rejected', 'needs_changes', 'blocked', 'needs_human_review'], required=True)
    p.add_argument('--notes', required=True)
    p.add_argument('--decided-at', required=True)
    p.add_argument('--pr-number', type=int)
    p.add_argument('--merge-commit-sha')
    p.add_argument('--comment-url')
    p.add_argument('--qa-packet-id')
    p.set_defaults(func=cmd_record_decision)

    p = sub.add_parser('materialize-coder-brief')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--package-id-external', required=True)
    p.add_argument('--brief-id-external')
    p.add_argument('--require-ready', action='store_true')
    p.add_argument('--allow-parallel-ready', action='store_true')
    p.set_defaults(func=cmd_materialize_coder_brief)

    p = sub.add_parser('materialize-architect-packet')
    p.add_argument('--manifest')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--package-id-external', required=True)
    p.add_argument('--allow-parallel-ready', action='store_true')
    p.add_argument('--packet-project', default='fractal-core')
    p.add_argument('--repo', required=True)
    p.add_argument('--branch', default='main')
    p.add_argument('--accepted-pr-number', type=int, required=True)
    p.add_argument('--accepted-pr-url', required=True)
    p.add_argument('--closed-issue-number', type=int, required=True)
    p.add_argument('--closed-issue-url', required=True)
    p.add_argument('--next-issue-number', type=int, required=True)
    p.add_argument('--next-issue-url', required=True)
    p.add_argument('--baseline-file', required=True)
    p.add_argument('--remaining-gap')
    p.add_argument('--next-move', action='append')
    p.add_argument('--focus', action='append')
    p.add_argument('--keep-stable', action='append')
    p.add_argument('--governance-reminder', action='append')
    p.add_argument('--pr-starter-branch')
    p.add_argument('--pr-starter-title')
    p.add_argument('--pr-starter-body-linkage')
    p.add_argument('--message-id')
    p.add_argument('--correlation-id')
    p.add_argument('--created-at')
    p.add_argument('--output')
    p.add_argument('--review-output')
    p.add_argument('--persist-db', action='store_true')
    p.add_argument('--skip-source-sync', action='store_true')
    p.set_defaults(func=cmd_materialize_architect_packet)

    p = sub.add_parser('materialize-slice-result-packet')
    p.add_argument('--manifest')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--package-id-external', required=True)
    p.add_argument('--brief-id-external', required=True)
    p.add_argument('--allow-nonready-brief', action='store_true')
    p.add_argument('--packet-project', default='fractal-core')
    p.add_argument('--to-role', default='techlead')
    p.add_argument('--repo', required=True)
    p.add_argument('--issue-number', type=int, required=True)
    p.add_argument('--issue-url', required=True)
    p.add_argument('--pr-number', type=int, required=True)
    p.add_argument('--pr-url', required=True)
    p.add_argument('--branch', required=True)
    p.add_argument('--dev-input-file', required=True)
    p.add_argument('--message-id')
    p.add_argument('--correlation-id')
    p.add_argument('--created-at')
    p.add_argument('--output')
    p.add_argument('--review-output')
    p.add_argument('--persist-db', action='store_true')
    p.set_defaults(func=cmd_materialize_slice_result_packet)

    p = sub.add_parser('materialize-worker-result-packet')
    p.add_argument('--manifest')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--package-id-external', required=True)
    p.add_argument('--brief-id-external', required=True)
    p.add_argument('--allow-nonready-brief', action='store_true')
    p.add_argument('--packet-project', default='fractal-core')
    p.add_argument('--worker-role', choices=['python-team', 'frontend-dev', 'backend-dev', 'infra-dev', 'docs-dev'], required=True)
    p.add_argument('--worker-family', default='implementation')
    p.add_argument('--result-type', required=True)
    p.add_argument('--to-role', default='techlead')
    p.add_argument('--repo', required=True)
    p.add_argument('--issue-number', type=int, required=True)
    p.add_argument('--issue-url', required=True)
    p.add_argument('--pr-number', type=int, required=True)
    p.add_argument('--pr-url', required=True)
    p.add_argument('--branch', required=True)
    p.add_argument('--worker-input-file', required=True)
    p.add_argument('--source-assignment-path', required=True)
    p.add_argument('--source-assignment-message-id')
    p.add_argument('--source-assignment-type', required=True)
    p.add_argument('--message-id')
    p.add_argument('--correlation-id')
    p.add_argument('--created-at')
    p.add_argument('--output')
    p.add_argument('--review-output')
    p.add_argument('--persist-db', action='store_true')
    p.set_defaults(func=cmd_materialize_worker_result_packet)

    p = sub.add_parser('materialize-qa-verification-packet')
    p.add_argument('--manifest')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--package-id-external', required=True)
    p.add_argument('--brief-id-external', required=True)
    p.add_argument('--packet-project', default='fractal-core')
    p.add_argument('--to-role', default='techlead')
    p.add_argument('--repo', required=True)
    p.add_argument('--issue-number', type=int, required=True)
    p.add_argument('--issue-url', required=True)
    p.add_argument('--pr-number', type=int, required=True)
    p.add_argument('--pr-url', required=True)
    p.add_argument('--branch', required=True)
    p.add_argument('--qa-input-file', required=True)
    p.add_argument('--verification-status')
    p.add_argument('--source-packet-path')
    p.add_argument('--message-id')
    p.add_argument('--correlation-id')
    p.add_argument('--created-at')
    p.add_argument('--output')
    p.add_argument('--review-output')
    p.add_argument('--persist-db', action='store_true')
    p.set_defaults(func=cmd_materialize_qa_verification_packet)

    p = sub.add_parser('materialize-delivery-review-packet')
    p.add_argument('--manifest')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--package-id-external', required=True)
    p.add_argument('--brief-id-external', required=True)
    p.add_argument('--packet-project', default='fractal-core')
    p.add_argument('--to-role', default='techlead')
    p.add_argument('--repo', required=True)
    p.add_argument('--issue-number', type=int, required=True)
    p.add_argument('--issue-url', required=True)
    p.add_argument('--pr-number', type=int, required=True)
    p.add_argument('--pr-url', required=True)
    p.add_argument('--branch', required=True)
    p.add_argument('--review-type', default='delivery_architecture_review')
    p.add_argument('--result-type', required=True)
    p.add_argument('--delivery-input-file', required=True)
    p.add_argument('--source-assignment-path', required=True)
    p.add_argument('--source-assignment-message-id')
    p.add_argument('--source-assignment-type', required=True)
    p.add_argument('--message-id')
    p.add_argument('--correlation-id')
    p.add_argument('--created-at')
    p.add_argument('--output')
    p.add_argument('--review-output')
    p.add_argument('--persist-db', action='store_true')
    p.set_defaults(func=cmd_materialize_delivery_review_packet)

    p = sub.add_parser('materialize-techlead-assignment-packet')
    p.add_argument('--manifest')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--package-id-external', required=True)
    p.add_argument('--brief-id-external', required=True)
    p.add_argument('--packet-project', default='fractal-core')
    p.add_argument('--target-role', choices=['delivery-architect', *TEAM_WORKER_CLI_CHOICES, 'qa'], required=True)
    p.add_argument('--repo', required=True)
    p.add_argument('--issue-number', type=int, required=True)
    p.add_argument('--issue-url', required=True)
    p.add_argument('--pr-number', type=int, required=True)
    p.add_argument('--pr-url', required=True)
    p.add_argument('--branch', required=True)
    p.add_argument('--canonical-branch')
    p.add_argument('--role-branch')
    p.add_argument('--branch-owner-role')
    p.add_argument('--lineage-state')
    p.add_argument('--lineage-action')
    p.add_argument('--source-branch')
    p.add_argument('--superseded-branch')
    p.add_argument('--worktree-hint')
    p.add_argument('--reset-reason')
    p.add_argument('--assignment-type', required=True)
    p.add_argument('--assignment-summary', required=True)
    p.add_argument('--allowed-result-type', action='append', required=True)
    p.add_argument('--source-packet-path')
    p.add_argument('--source-packet-message-id')
    p.add_argument('--message-id')
    p.add_argument('--correlation-id')
    p.add_argument('--created-at')
    p.add_argument('--output')
    p.add_argument('--review-output')
    p.add_argument('--persist-db', action='store_true')
    p.set_defaults(func=cmd_materialize_techlead_assignment_packet)

    p = sub.add_parser('materialize-techlead-decision-packet')
    p.add_argument('--manifest')
    p.add_argument('--project-slug', default=PAA_PROJECT_SLUG)
    p.add_argument('--package-id-external', required=True)
    p.add_argument('--brief-id-external', required=True)
    p.add_argument('--packet-project', default='fractal-core')
    p.add_argument('--repo', required=True)
    p.add_argument('--issue-number', type=int, required=True)
    p.add_argument('--issue-url', required=True)
    p.add_argument('--pr-number', type=int, required=True)
    p.add_argument('--pr-url', required=True)
    p.add_argument('--branch', required=True)
    p.add_argument('--canonical-branch')
    p.add_argument('--role-branch')
    p.add_argument('--branch-owner-role')
    p.add_argument('--lineage-state')
    p.add_argument('--lineage-action')
    p.add_argument('--source-branch')
    p.add_argument('--superseded-branch')
    p.add_argument('--worktree-hint')
    p.add_argument('--reset-reason')
    p.add_argument('--to-role', choices=['authority-architect', 'techlead'], default='authority-architect')
    p.add_argument('--target-role', choices=TEAM_WORKER_DECISION_CHOICES)
    p.add_argument('--decision-type', required=True)
    p.add_argument('--decision-rationale', required=True)
    p.add_argument('--next-assignment-type')
    p.add_argument('--work-item-status-update-intent', required=True)
    p.add_argument('--source-packet-path', required=True)
    p.add_argument('--source-packet-message-id')
    p.add_argument('--message-id')
    p.add_argument('--correlation-id')
    p.add_argument('--created-at')
    p.add_argument('--output')
    p.add_argument('--review-output')
    p.add_argument('--persist-db', action='store_true')
    p.set_defaults(func=cmd_materialize_techlead_decision_packet)

    return parser
