"""Repository interfaces and concrete implementations for PAA data access."""

from .component_design import (
    CoderBriefRealizationTargetRecord,
    ComponentDesignRepository,
    ComponentElementRealizationRecord,
    ComponentElementRealizationTypeRecord,
    ComponentElementRecord,
    ComponentElementTypeRecord,
    ComponentRecord,
    PostgresComponentDesignRepository,
)
from .execution_package import (
    ExecutionPackageInstallRecord,
    ExecutionPackageOverlayRecord,
    ExecutionPackageRepository,
    InstalledExecutionContextRecord,
    PostgresExecutionPackageRepository,
)
from .implementation_plan import (
    ImplementationPlanActivityDependencyRecord,
    ImplementationPlanActivityDependencyUpsertSpec,
    ImplementationPlanActivityRecord,
    ImplementationPlanActivityUpsertSpec,
    ImplementationPlanRecord,
    ImplementationPlanRepository,
    ImplementationPlanUpsertSpec,
    ImplementationPlanVerificationSurfaceRecord,
    PostgresImplementationPlanRepository,
)
from .runtime_event import (
    AcceptanceEventRecord,
    AutomationRunEventRecord,
    AutomationRunRecord,
    HandoffRecord,
    PostgresRuntimeEventRepository,
    QueueMessageRecord,
    RuntimeEventRepository,
    TransitionInputRecord,
)
from .workflow_state import (
    PostgresWorkflowStateRepository,
    QueueClaimRecord,
    WorkflowStateRecord,
    WorkflowStateRepository,
    WorkflowStateUpsertSpec,
    WorkflowTransitionAppendSpec,
    WorkflowTransitionRecord,
)

__all__ = [
    "AcceptanceEventRecord",
    "AutomationRunEventRecord",
    "AutomationRunRecord",
    "CoderBriefRealizationTargetRecord",
    "ComponentDesignRepository",
    "ComponentElementRealizationRecord",
    "ComponentElementRealizationTypeRecord",
    "ComponentElementRecord",
    "ComponentElementTypeRecord",
    "ComponentRecord",
    "ExecutionPackageInstallRecord",
    "ExecutionPackageOverlayRecord",
    "ExecutionPackageRepository",
    "HandoffRecord",
    "ImplementationPlanActivityDependencyRecord",
    "ImplementationPlanActivityDependencyUpsertSpec",
    "ImplementationPlanActivityRecord",
    "ImplementationPlanActivityUpsertSpec",
    "ImplementationPlanRecord",
    "ImplementationPlanRepository",
    "ImplementationPlanUpsertSpec",
    "ImplementationPlanVerificationSurfaceRecord",
    "InstalledExecutionContextRecord",
    "PostgresComponentDesignRepository",
    "PostgresExecutionPackageRepository",
    "PostgresImplementationPlanRepository",
    "PostgresRuntimeEventRepository",
    "PostgresWorkflowStateRepository",
    "QueueClaimRecord",
    "QueueMessageRecord",
    "RuntimeEventRepository",
    "TransitionInputRecord",
    "WorkflowStateRecord",
    "WorkflowStateRepository",
    "WorkflowStateUpsertSpec",
    "WorkflowTransitionAppendSpec",
    "WorkflowTransitionRecord",
]
